package com.aihypetycoon.app.game

data class Employee(
    val id: String,
    val roleId: String,
    val name: String,
    val hiredOn: Int,
    val morale: Double = 72.0,
)
data class ModelJob(val specId: String, val remaining: Int, val total: Int)
data class FinishedModel(
    val id: String,
    val specId: String,
    val quality: Double,
    val shipped: Boolean,
    val fakeBench: Boolean,
    val launched: Boolean = false,
)
data class Product(
    val id: String,
    val name: String,
    val modelId: String,
    val users: Int,
    val arpu: Double,
    val quality: Double,
)
data class GpuOrder(val qty: Int, val remaining: Int)
data class Competitor(val id: String, val name: String, val hype: Double, val valuation: Double)
data class NewsItem(val id: String, val day: Int, val text: String, val tone: String)
data class Effect(
    val cash: Double = 0.0,
    val hype: Double = 0.0,
    val quality: Double = 0.0,
    val research: Double = 0.0,
    val compute: Double = 0.0,
    val gpus: Int = 0,
    val scandal: Double = 0.0,
    val heat: Double = 0.0,
    val evil: Double = 0.0,
    val waitlist: Int = 0,
    val users: Int = 0,
    val morale: Double = 0.0,
    val valuationMul: Double = 0.0,
    val log: String? = null,
    val logTone: String = "ok",
    val ending: String? = null,
    val shortageDays: Int = 0,
    val acquireOffer: Boolean = false,
)
data class EventChoice(val id: String, val label: String, val hint: String, val effects: Effect)
data class GameEvent(
    val id: String,
    val title: String,
    val body: String,
    val weight: Int,
    val minDay: Int = 0,
)
data class RoleDef(
    val id: String,
    val name: String,
    val blurb: String,
    val signing: Int,
    val salaryMo: Int,
    val research: Double,
    val hype: Double,
    val quality: Double,
    val computeEff: Double,
    val heat: Double,
    val scandalDecay: Double,
    val demoBoost: Double,
    val product: Double = 0.0,
)
data class ModelSpec(
    val id: String,
    val name: String,
    val blurb: String,
    val days: Int,
    val compute: Int,
    val researchNeed: Int,
    val qualityCap: Int,
    val hypeOnShip: Int,
    val arpu: Double = 0.08,
)
data class RoundDef(
    val id: String,
    val name: String,
    val blurb: String,
    val minHype: Int,
    val minValuation: Long,
    val raise: Long,
    val dilution: Double,
)
data class GameState(
    val version: Int = 2,
    val seed: Long,
    val rng: Int,
    val day: Int,
    val speed: Int,
    val company: String,
    val cash: Double,
    val equity: Double,
    val hype: Double,
    val quality: Double,
    val research: Double,
    val compute: Double,
    val gpus: Int,
    val scandal: Double,
    val heat: Double,
    val evil: Double,
    val valuation: Double,
    val lastRound: String?,
    val nextRound: String,
    val pivots: Int,
    val lastPivotDay: Int,
    val gpuShortageUntil: Int,
    val employees: List<Employee>,
    val training: ModelJob?,
    val models: List<FinishedModel>,
    val products: List<Product> = emptyList(),
    val users: Int = 0,
    val revenueToday: Double = 0.0,
    val listed: Boolean = false,
    val stockPrice: Double = 0.0,
    val shares: Int = 10_000_000,
    val market: String = "quiet",
    val marketDaysLeft: Int = 48,
    val competitors: List<Competitor> = emptyList(),
    val gpuOrders: List<GpuOrder> = emptyList(),
    val morale: Double = 74.0,
    val demoCooldown: Int,
    val waitlistCooldown: Int,
    val stealCooldown: Int,
    val fakeCooldown: Int,
    val news: List<NewsItem>,
    val eventId: String?,
    val waitlist: Int,
    val papersStolen: Int,
    val fakeBenches: Int,
    val daysBroke: Int,
    val flags: Map<String, Boolean>,
    val ending: String?,
    val acquireOffer: Double,
    val lastRealMs: Long,
    val toast: String? = null,
)
